apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-zookeeper.yaml
  - 02-nifi-configmap.yaml
  - 03-nifi-secret.yaml
  - 05-nifi-services.yaml
  - 04-nifi-statefulset.yaml   # StatefulSet al final (depende de los dem√°s)
